### ISSUE TITLE
Add More Dynamic Prompts

### ISSUE THREAD

**Issue by Yiannis128** [Yiannis128/esbmc-ai#99]
# Tasks

- [ ] Design and add prompts for each vulnerability type that is going to be supported.
- [ ] Refine and improve the generic prompt.

# Scenarios

The following errors are recognized (this list is not exhaustive):

- [x] `division by zero`
- [ ] `dereference failure: NULL pointer`
